### ISSUE TITLE
Bower installable missing for the component

### ISSUE THREAD

**Issue by mayur-pearson** [Pearson-Higher-Ed/o-app-header#10]
We couldn't find the bower installable component for this module.

**Comment by aarmour** [comment]
You will need to add the following to your `.bowerrc` file:

```JSON
{
  "registry": {
    "search": [
      "https://origami.pearsoned.com/registry",
      "https://bower.herokuapp.com"
    ]
  }
}
```

Then `bower install o-app-header` should work.
