### ISSUE TITLE
Missing pipe separator between items

### ISSUE THREAD

**Issue by parkerpearson** [Pearson-Higher-Ed/o-app-header#11]
There should be a pipe between 'Help' and 'Sign In' or the user's name.

cc @edzee

**Comment by aarmour** [comment]
I continued to wrangle with this today but still don't have a solution that isn't a buggy hack. Hiding the divider when a menu is open is the problem that's holding me back. I'm going to defer for now, but we should probably consider alternatives.

**Comment by parkerpearson** [comment]
@bluemeredith @edzee thoughts on this? I'd probably just go with dropping the pipe entirely.

**Comment by edzee** [comment]
Dropping it sounds like the way to go.  I think there's enough space built-in between items in the header to act as a visual separator.

**Comment by aarmour** [comment]
Closing. If we end up needing to visually distinguish the menu from other items, it will go in a future release and require a new story.
