### ISSUE TITLE
Option for removing 'o-header--fixed' class?

### ISSUE THREAD

**Issue by bobd9978** [Pearson-Higher-Ed/o-app-header#15]
Our page layout employs a 'sticky footer' layout which breaks when the header display is fixed. Is there any way to remove the o-header--fixed class or have it be an option?

**Comment by aarmour** [comment]
@bobd9978 There's definitely no technical reason it cannot be exposed as an option. UX made the decision for the application header to always be fixed. On the other hand, there is no standard footer—or any standard layout, for that matter—so it seems reasonable to expose it. @parkerpearson, what are your thoughts?

(cc @Pearson-Higher-Ed/design-ux).

**Comment by parkerpearson** [comment]
@bobd9978 which application are you working on for this? If you have some screenshots of how the header is interacting with the footer that might be useful.

We are using a fixed header to stay consistent with the current experience and to make sure that global navigation and features (such as returning home or accessing help) are available in a predictable way.

**Comment by bobd9978** [comment]
@parkerpearson Better than screenshots, here are some actual pages:
Start here: https://console.pearson.com/signin

The current login pages developed by the Pi group start with the login page and continue on to Forgot Your Username or Password (follow link). There are a half dozen more in this suite, jsp based, old-school jsp environment with home-grown javascript modules. 

If you follow the Create an Account link there you are on pages developed by the Console group. As it turns out, the Pi group is taking over the Create Account page. These are currently two different code bases in Pi (the old jsp one and new angular spa one). The future direction is to move all of the jsp pages into the single page app angular one. 

The page layouts are different between these. The Pi pages use a 'sticky footer' implementation with a non-fixed header. This seemed like the right choice at the time as the vertical space used is always small. It is for these pages that I was hoping to just stick the header in and not have to redo the page layout. Pinning the footer to the bottom was a good experience and rarely would the user ever have to scroll and lose the header. 

The Create Account page is a different story. Being quite tall, I understand the design decision to want to keep the header fixed (for help and sign in/out links). Currently this page has a semi-sticky footer. When the viewport is smaller than the content, the main content overlaps the footer. I would like to fix this. 

Do you know of any layout implementations with a fixed header and footer that don't have this overlapping issue with the footer?

**Comment by parkerpearson** [comment]
@bobd9978 for the shorter Pi pages (sign in, forgot password, etc) it seems like the fixed header should behave identically to a non-fixed version since you never have the opportunity to scroll. Unless I'm misunderstanding the design.

For the footer, it would be nice to have it stick to the bottom when the content is too short for scrolling, but then behave normally and just append itself at the end of the content when the page does scroll. I'm not aware of a technique for this, although @aarmour or another developer might have some ideas.

(Sorry for the delay in getting back to you.)

**Comment by bobd9978** [comment]
Thanks for getting back, @parkerpearson . I was just about to report that found and integrated a good implementation for a fixed header and sticky footer. The key behavior that I was after was the sticky footer not overlapping the content, an issue that most implementations suffer from. I also didn't want the header sliding behind the content as is evident in the current Create Account page. 

So, I won't be needing the o-header--fixed class exposed. Thanks for offering, Adam.

**Comment by parkerpearson** [comment]
@bobd9978 sounds good!
