### ISSUE TITLE
Pearson logo error (410 Gone)

### ISSUE THREAD

**Issue by mayur-pearson** [Pearson-Higher-Ed/o-app-header#8]
If we try to add the script using build-bundle the http get req for the logo says 410 gone

<script src="https://origami-stg.pearsoned.com/build/bundles/js?autoinit=0&modules=o-app-header@0.0.5"></script>
<link rel="stylesheet" href="https://origami-stg.pearsoned.com/build/bundles/css?modules=o-app-header@0.0.5">

**Comment by aarmour** [comment]
This is an issue with the build service, not the module itself.
