### ISSUE TITLE
User Given Name doesn't appear for the dropdown

### ISSUE THREAD

**Issue by mayur-pearson** [Pearson-Higher-Ed/o-app-header#9]
The user name doesn't appear on the header. dropdown

**Comment by aarmour** [comment]
Could you provide an example of how you are configuring the `user` property?

**Comment by mayur-pearson** [comment]
var _session = loginService.getSession();
            var user_name = 'Profile';
            if (_session) {
                user_name = _session['first_name'] + ' ' + _session['last_name'];
            }

            var config = {
                session: 'piSession',
                user: { givenName: user_name }
            };

**Comment by aarmour** [comment]
Based on your example, the only way I can duplicate is if `_session.first_name` and `_session.last_name` are empty strings.

Also, though not related to the display issue, `givenName` should be first name only, not a concatenation of first and last name.

**Comment by mayur-pearson** [comment]
We checked it via debugger, the string is not empty

**Comment by aarmour** [comment]
This should be resolved in the latest version.
